### ISSUE TITLE
Adicionar guia de contribuição para repositório

### ISSUE THREAD

**Issue by Matheus456** [mecassauro/RADAR-backend#15]
**Descrição**

Adicionar guia de contribuição para repositório.

**Objetivo**

Padronizar a contribuição de interessados no projeto.

**Tarefas**

Tarefas a serem realizadas, se existirem.

- [x] Criar o documento CONTRIBUTING.md

**Comment by byronkamal** [comment]
Issue moved to [mecassauro/covinfo-backend #20](https://github.com/mecassauro/covinfo-backend/issues/20) via [**ZenHub**](https://www.zenhub.com/)
